### ISSUE TITLE
Let us search sales

### ISSUE THREAD

**Issue by kriNon** [hugoattal/OrbitalMarket#13]
Currently the February Sale is going on here: www.unrealengine.com/marketplace/en-US/event-sale
It would be awesome to be able to view it in orbital market.

**Comment by TheHerobrine** [comment]
@kriNon You're right, I'm trying to make this work for today 😉

**Comment by TheHerobrine** [comment]
@kriNon Done, discount is now displayed and you can filter only discounted product: https://orbital-market.com/search

One thing is not ready yet: when filtering by price, discount is not taken into account...
