### ISSUE TITLE
Feature Request: Category select & tag filter like in Unreal Marketplace

### ISSUE THREAD

**Issue by 4getter** [hugoattal/OrbitalMarket#20]
It'd be nice to have the feature to select the category(Blueprints, Plugins, Weapons etc) that you have in Unreal Marketplace & also tag filter feature where you can select or negate tags when searching for assets.

These two features are the reason I use Unreal Marketplace instead of Orbtal a lot of times.

**Comment by hugoattal** [comment]
Category is done! I'm not sure if I'll do tag yet, since:
- they're really not homogeneous
- it's quite hard to retrieve it for the marketplace...

![image](https://user-images.githubusercontent.com/4563971/151809743-a10bb47a-d461-40a8-9334-240355f7b93d.png)
