### ISSUE TITLE
Unreal Engine 4.27 not available in engine filter

### ISSUE THREAD

**Issue by Tezenari** [hugoattal/OrbitalMarket#21]
# Overview
It appears that Unreal Engine 4.27 is currently not available within the engine filter. It would be ideal to have 4.27 as an option to filter out the marketplace items that haven't been updated to the latest Unreal Engine version.

# Screenshots
![image](https://user-images.githubusercontent.com/21698404/151722596-fb675f22-2fe7-4974-8d2c-911c5506ca8a.png)

**Comment by hugoattal** [comment]
Oops... forgot to update this picker, it's now fixed!
