### ISSUE TITLE
No assets are loading

### ISSUE THREAD

**Issue by MrGoatsy** [hugoattal/OrbitalMarket#24]
The search wheel just keeps spinning.

When visiting a specific assets I get this message:
`{"statusCode":500,"error":"Internal Server Error","message":"connect ECONNREFUSED 127.0.0.1:27017"}`

**Comment by hugoattal** [comment]
Yeah, sorry for this... This happens when my host provider restart my server (for whatever reason). Usually, I fix it under 24h.

I should automate the start of everything when the server start, for now I just do it manually...
