### ISSUE TITLE
Feature Request: Advanced filtering / user data?

### ISSUE THREAD

**Issue by namrog84** [hugoattal/OrbitalMarket#25]
It'd be great to have some additional filtering.

* There is an increase in spam/low quality sellers, please add a way to maybe add a regex string to just hide from showing up.
    * Allow us a comma or | separated list of sellers we want to exclude.
    * Alternatively, instead of exclusionary, maybe add a way for people to create curated lists of included sellers only.

Alternatively, I know right now we don't have a user account at oribital-market, but if you added a way to login. (p.s. I'd honesty pay for this feature (OrbitalMarket PRO)
1. Allow me to sync my user account somehow so I can hide/see item I already own.
2. Keep a saved list of permanent sellers to exclude from showing up.

**Comment by hugoattal** [comment]
Hey, thank you very much for the suggestion :) !

> Allow us a comma or | separated list of sellers we want to exclude.

What about a simple blacklist that is saved on your local storage? This should be fairly easy and quick to implement...
The "dashboard" is already available in the top left corner to list all your favs for now.

> Alternatively, instead of exclusionary, maybe add a way for people to create curated lists of included sellers only.

I love the idea of curated lists! But to do so, I'll have to create a user account system which is pretty complex

> Allow me to sync my user account somehow so I can hide/see item I already own.

This would be veeeeery complex as there's no public API to get your already owned assets. What about manually marking your already owned assets?

> Keep a saved list of permanent sellers to exclude from showing up.

That would be the solution to your first suggestion

---

I believe more and more people are requesting user accounts, and that would make possible a lot of cool features (curated lists, blacklist, owned assets, update notification/mails when there is a discount or a price change...). I think I may end up building it.

Just out of curiosity, how much do you think such a feature should cost? I'll probably make it free with a donation button, but I'm curious on what you had in mind. If people were willing to pay for some features, I could allocate a lot more time to build Orbital Market, even make a custom launcher for the Unreal Engine where you would be able to download any version of an asset for example.

**Comment by namrog84** [comment]
Local storage blacklist, absolutely would work for me and I think would solve the problem.

Marking my own assets in a way that's saved locally in browser absolutely would work.   I'd have no problem doing that.


It'd be even better if there was a way to export/save this stuff locally so incase the cache ever gets messed up, I can reimport it easily.  


I think some of this would be entirely possible using local storage/cookie or whatever,  and throw in an export/import mechanism and you could possibly get a good chunk of this functionality without any actual user account.  I know it'd be enough to satisfy me.

**Comment by ryobg** [comment]
+1 for simple/local filtering list based at least on author name (ID).

**Comment by hugoattal** [comment]
Done!

![image](https://github.com/user-attachments/assets/de115982-a4bc-4625-842f-b54a2c6418ef)

**Comment by namrog84** [comment]
Much appreciation! Thanks!

Is there a way to hide or mark as owned that I overlooked somewhere?

**Comment by hugoattal** [comment]
You can mark them as favorites, but then you won't be able to differentiate the ones that you have from the ones that you own 🤔...

I'll need to add a way to create different favlist.
