### ISSUE TITLE
Websites states Unreal Engine version 5 and 5.01, it should be version 5.1

### ISSUE THREAD

**Issue by MrGoatsy** [hugoattal/OrbitalMarket#26]
The title.

**Comment by hugoattal** [comment]
To me `5.01` is the same as `5.1`. I chose to go for `5.01` to have a homogeneous display with always two digits after the dot.

Also, it's also better for sorting, here's what it will do with using one digit for single digit versions:
5.0 < 5.1 < 5.10 < 5.11 < ... < 5.18 < 5.19 < 5.2 < 5.20 < 5.21 ... < 5.29 < 5.3 < 5.30 < 5.31 ...

But if we keep two digits:
5.00 < 5.01 < 5.02 < 5.03 < ... < 5.09 < 5.10 < 5.11 ...

**Comment by MrGoatsy** [comment]
5.01 is a revision of 5.0 used for bug fixes, in 5.1 new features get introduced.

**Comment by hugoattal** [comment]
Hum, I think you meant 5.0.1 being a revision of 5.0.

Though, I made a little research, and according to semver (https://semver.org/), and they say this:
![image](https://user-images.githubusercontent.com/4563971/202920512-79105b8b-9248-4995-a0d8-5a43cee04068.png)

So I'll update Orbital Market to display correct semver...

**Comment by hugoattal** [comment]
Done!
