### ISSUE TITLE
Feature Request: Sort by price?

### ISSUE THREAD

**Issue by Jason-Terry** [hugoattal/OrbitalMarket#29]
Would be awesome to see sort by price ascending / descending for us habitual browsers.

**Comment by hugoattal** [comment]
Hello, this has already been requested, but I'm not sure how to proceed...

Results takes into account search score (how close it matches your request) and popularity (using the reviews).
If I added a feature to sort by price, you might get results really far from your request, defeating the purpose of the search engine.

Maybe you could use the price filter instead?
![image](https://user-images.githubusercontent.com/4563971/212661375-28c20ff6-1106-4d08-8bfc-9210930e695e.png)

What would be your use case? Maybe I can find a better solution for what you're looking to achieve...

**Comment by ryobg** [comment]
Ayo! Came here for 2nd time for that. It is not about the Searching so much to me, but just for the listing/browsing the market.

If you want to allow this for the Searching, probably you can low-res the word matching weights and then sort by price. Just a quick idea.

**Comment by vlader08** [comment]
Please consider adding strict keyword contained in title for searching then you can have the price sorting as well.
For example i search for 'flare' looking for some lens flares or stuff to add to rockets to make their engine glow and it brings up audio assets which doesn't help.

**Comment by hugoattal** [comment]
@vlader08 You can remove audio assets by checking the "FX" categories (and then only have FX assets)
![image](https://github.com/hugoattal/OrbitalMarket/assets/4563971/5597a4ad-fa9b-4686-8c98-6aad0809896f)

Also, if you want to remove some kind of flares (like "retro" flares for whatever reason), you can search this: `lens flare -retro`

Lastly, the search is already case insensitive

---

About the title: title already contain a heavier weight than the content, but some flares might not have the name "Flare" in the title (for example, I found the asset "Realistif Starter VFX Pack" which contains flares)

About the price: once again, it's not really possible to sort by price without removing the "smart" sort and have a useless search output.

**Comment by hugoattal** [comment]
Thanks a lot ❤️

Guess I'll add the pricing sort you guys all ask for in the next version, but I'm confident it'll be pretty useless 😕 (though, there's already a name sorting which is a lot more useless)

**Comment by hugoattal** [comment]
@vlader08 Thanks a lot for your sponsoring ❤️! The price sorting is now available 😉

![image](https://github.com/hugoattal/OrbitalMarket/assets/4563971/7ea50cce-95fb-44ce-bded-d9b75aa01f92)

**Comment by vlader08** [comment]
@hugoattal You're more than welcome, I own the electronic nodes and probably will get the darker nodes as well :P
Just tested the price sorting and it does sort just fine for my needs, the extra filter of categories helps to keep it on track.

**Comment by ryobg** [comment]
You can always check on how much this feature is used I suppose. To me, it looks useful.
