### ISSUE TITLE
Add filter with price (range), discount, engine, tags

### ISSUE THREAD

**Issue by hugoattal** [hugoattal/OrbitalMarket#3]
Lot of missing filters 😅...

**Comment by TheHerobrine** [comment]
Price and engine done here https://github.com/TheHerobrine/OrbitalMarket/commit/e46645015ea0bf84b74d29a7ae5ab3ad714ffecf 😎 !

**Comment by ryobg** [comment]
Just a reminder here that 5.2. and 5.3 are missing from the Engine filter.

**Comment by hugoattal** [comment]
@ryobg Oops, sorry, fixed! (I should do something so that it's automatic... for now, I have to manually update it)
