### ISSUE TITLE
Feature Request: Vault Viewer?

### ISSUE THREAD

**Issue by sclark39** [hugoattal/OrbitalMarket#35]
It would be great to be able to quickly browse items in my vault or filter the search by what I already own.

**Comment by hugoattal** [comment]
You can now import assets from your vault:

- Just go to https://www.unrealengine.com/marketplace/en-US/vault
- Select showing 100 per page, then copy the whole page (Ctrl+A/Ctrl+C)
- In the [Orbital Market dashboard](https://orbital-market.com/dashboard), click on "Import from clipboard" (you must accept clipboard reading)
- Repeat for every page.

Then you can search your vault by clicking on the "Favorites" button on the [search page](https://orbital-market.com/search)
