### ISSUE TITLE
Can't correctly filter on author

### ISSUE THREAD

**Issue by BlenderGamer** [hugoattal/OrbitalMarket#36]
As I browsed through free section today, saw a content from "Unreal Online Learning". Wanted to see others pack they provide and selected the author (click on the link to filter). Only one product appear, though I know there are multiples, and it was not even the one I saw in the first place.

How to reproduce:
1) Search "Unreal Online Learning" products using plain text search
https://orbital-market.com/search?searchText=Unreal+Online+Learning&sortField=popularity
2) Filter by clicking on one of "Unreal Online Learning" author link
https://orbital-market.com/search?searchText=author%3A%22Unreal+Online+Learning%22

**Comment by hugoattal** [comment]
Oh, seems link there are TWO "Unreal Online Learning" with different Unreal Id... I'll fix that, thanks for pointing it out!

![image](https://github.com/hugoattal/OrbitalMarket/assets/4563971/2203c164-fb36-4dcb-b4e2-287a992ec26b)

**Comment by hugoattal** [comment]
Fix! It should now work as expected!
