### ISSUE TITLE
Categories checkboxes not updated on page load

### ISSUE THREAD

**Issue by ryobg** [hugoattal/OrbitalMarket#42]
Select some Categories, Reload/Refresh/Bookmark&Open later the page, no checkboxes are visible, but their filtering capabilities are actually applied under the hood.

![image](https://github.com/hugoattal/OrbitalMarket/assets/13996376/c6dd9a02-b90d-4839-ba0d-3c9cce7d046d)

**Comment by hugoattal** [comment]
I managed to reproduce, looking into it 😉
