### ISSUE TITLE
Add filter by amount of discount

### ISSUE THREAD

**Issue by MattL-V** [hugoattal/OrbitalMarket#48]
During big sales events in UE Marketplace, you can easily select an asset category and filter all assets with a 70% discount.
In Orbital, you have 10% discount assets mixed with 70% discount assets lying around.
You have only one function: to hide all assets with no discount at all.
Unfortunately, this makes the need to return to the obsolete UE marketplace to explore assets deals with this vital function.

**Comment by hugoattal** [comment]
Done
![image](https://github.com/hugoattal/OrbitalMarket/assets/4563971/e8db38c7-e8e1-41e3-bef9-5db10d9b0e35)
