### ISSUE TITLE
Hide all assets from specific author

### ISSUE THREAD

**Issue by MattL-V** [hugoattal/OrbitalMarket#49]
There are many sellers who infiltrate the UE marketplace with 100+ low-quality AI-generated assets.
This massively hinders the asset-searching experience.
It would be greatly improved by a feature to hide products from unwanted creators.

**Comment by hugoattal** [comment]
Still don't know how to approach this as there are no accounts in Orbital Market... Store this info in the localstorage (just like favorites)?

Maybe just add a button to hide all AI assets 🤔?

Doesn't the popular search filter out all those kinds of assets? Do you have a search input example?

**Comment by MattL-V** [comment]
“Popular” in the “2D” category already has AI assets in the first row.

I would not limit this to AI-only assets, as there are a lot of other sellers whose content is low quality or just definitely unwanted by the user. 
Especially in the art categories, many sellers can have dozens of assets you already know about and would rather not see again and again in every one of your searches.

Maybe you could do this by storing a local blacklist of authors.

**Comment by hugoattal** [comment]
Ok, I'll add this when I find a bit of time 🤔

**Comment by hugoattal** [comment]
Done!

![image](https://github.com/user-attachments/assets/3d75876a-10ea-457c-8522-0fa65ccefd7c)
