### ISSUE TITLE
Add “5.4” version to "Engine Range" scrollbar

### ISSUE THREAD

**Issue by MattL-V** [hugoattal/OrbitalMarket#50]
During the early period of a new engine version being released, it is important to have the ability to search for assets that support the current version along with assets that support the previous version. Most of them just didn't have the opportunity to update their assets, but they will in the near future.
And the user would rather not filter out those assets.
Sorting separately for assets already supporting the new version and assets that currently support only the previous version is tedious.

With the current range scrollbar, you can sort for "previous version" + "previous version"
But you can't search for  "previois version" + "current version", meaning many new assets supporting only the current version will be filtered out.

**Comment by hugoattal** [comment]
Oops, forgot this... I'm updating it!

**Comment by hugoattal** [comment]
Done!

![image](https://github.com/hugoattal/OrbitalMarket/assets/4563971/2b763076-6e57-4739-9cd3-2af480fe3bd2)

**Comment by MattL-V** [comment]
Please do the same for 5.5 version
Thanks!

**Comment by hugoattal** [comment]
@MattL-V Done!
