### ISSUE TITLE
The site does not work anymore

### ISSUE THREAD

**Issue by MrGoatsy** [hugoattal/OrbitalMarket#52]
No assets load any more.

**Comment by Jan-Jakub-Fleiser** [comment]
yep. 404 Not Found, 500 Internal Server Error and ECONNREFUSED

**Comment by hugoattal** [comment]
Aaaaarg, it's again a shutdown of the database... I have to fix this once and for all...Thanks for reporting it!
I'm not at home, I'll fix this in ~12h, sorry for this :/

**Comment by hugoattal** [comment]
Fixed! I'll try to update a few stuff for this to stop to happen, sorry for the delay...

**Comment by hugoattal** [comment]
(On a side note, I may or may not have deleted all the price history of products 😬...)
