### ISSUE TITLE
UI is broken

### ISSUE THREAD

**Issue by MattL-V** [hugoattal/OrbitalMarket#56]
Buttons as:
Detailed description
Technical description
Reviews
Questions
Price history

Are collapsing on top of each other, just as the sub-windows they open are overlaying the buttons bar.

**Comment by hugoattal** [comment]
Could you make a screenshot?

**Comment by MattL-V** [comment]
For example, here:
![image](https://github.com/user-attachments/assets/807483f4-5254-4038-9687-2b4c8d9550d0)

**Comment by hugoattal** [comment]
Hum, that's weird... What browser are you using? I can't reproduce on Chrome or Firefox...

**Comment by MattL-V** [comment]
I found the culprit.
Installing this extension on Chrome and Edge leads to a broken UI.
https://chromewebstore.google.com/detail/ai-content-detector-chat/kdngfaamkbbkdbemejnlkmjfpmndjdmb
It's weird because this extension should actually have nothing to do with altering the website's UI.
